version: '3.8'

services:
  knowledge-base:
    build: 
      context: ../knowledge-base
    ports:
      - "8082:8082"  # Using 8082 to avoid conflicts
    environment:
      - FLASK_ENV=development
      - PORT=8082
      - TRIEVE_HOST=http://localhost:8090  # Using localhost as recommended
      - TRIEVE_API_KEY=${ADMIN_API_KEY}
      - DATASET_ID=${DATASET_ID}
      - ORGANIZATION_ID=${ORGANIZATION_ID}
    network_mode: "host"  # This will allow direct localhost access

networks:
  default:
    name: host 