version: '3.8'

services:
  knowledge-base:
    build: 
      context: ../knowledge-base
    ports:
      - "8082:8082"  # Using 8082 to avoid conflicts
    environment:
      - FLASK_ENV=development
      - PORT=8082
      - TRIEVE_HOST=http://localhost:8090  # Using localhost as recommended
      - TRIEVE_API_KEY=${ADMIN_API_KEY}
      - DATASET_ID=${DATASET_ID}
      - ORGANIZATION_ID=${ORGANIZATION_ID}
    network_mode: "host"  # This will allow direct localhost access

  extraction-service:
    build:
      context: ../extraction-service
    ports:
      - "8083:8083"  # Using 8083 as defined in our service
    environment:
      - FLASK_ENV=development
      - PORT=8083
    volumes:
      - ../extraction-service/data:/app/data  # Mounting data directory to persist extracted files
    network_mode: "host"  # Using host network mode for consistency

networks:
  default:
    name: host 